name: links

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-node@v7
      with:
        node-version: '22'
        cache: 'npm'

    - name: Build site
      run: |
        npm ci
        npm run build

    - name: Restore lychee cache
      uses: actions/cache@v4
      with:
        path: .lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - name: Link Checker
      uses: lycheeverse/lychee-action@v2
      with:
        args: --verbose --no-progress --root-dir dist --cache --max-cache-age 1d -- dist/**/*.html
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
